{{- if and .Values.notifications.webhookToken (not .Values.notifications.routes) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poddoctor.fullname" . }}-webhook-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poddoctor.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.notifications.webhookToken | quote }}
{{- end }}
